subscriptions:
  - name: MyPodcast
    url: https://youtube.com
    retention_days: 14 # How old is the oldest video to download and keep locally
    initialize: True # Download the whole channel on first run
    download_last: 1 # Only download the last video at each run
    audio_only: True # Extract and keep audio only
    format: mp3      # Force end format
    filename_template: '%(id)s.%(ext)s' # Use this format for files saved from this subscription
  - name: MyPodcast2
    url: https://youtube.com
    retention_days: 14 # How old is the oldest video to download and keep locally
    initialize: True # Download the whole channel on first run
    download_last: 1 # Only download the last video at each run
    ydl_options: # Add custom youtube-dl options
      writesubtitles: True # Write subtitle file
    nfo_files: True # Generates .nfo files for each download and for the subscription
    private: True # Exclude from index

output_dir: /var/www/html/podcast/
url_root: https:///podcast.example.com/
youtube-dl-module: youtube-dl
index_enabled: False # Create an index.html file indexing the subscriptions
style_rss_feed: True # Add XSLT Styling to RSS Feed
